name: Release

on:
    push:
        tags:
            - 'v*'

jobs:
    release:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: '1.24'

            - name: Cache Go modules
              uses: actions/cache@v4
              with:
                  path: ~/go/pkg/mod
                  key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                  restore-keys: |
                      ${{ runner.os }}-go-

            - name: Download dependencies
              run: go mod download

            - name: Run tests
              run: go test -tags sqlite_fts5 -v ./...

            - name: Build for Linux AMD64
              run: |
                  GOOS=linux GOARCH=amd64 go build -tags sqlite_fts5 -o pdf-fts-Linux-x86_64 ./cmd/pdf-fts

            - name: Build for Linux ARM64
              run: |
                  GOOS=linux GOARCH=arm64 go build -tags sqlite_fts5 -o pdf-fts-Linux-aarch64 ./cmd/pdf-fts

            - name: Build for macOS AMD64
              run: |
                  GOOS=darwin GOARCH=amd64 go build -tags sqlite_fts5 -o pdf-fts-Darwin-x86_64 ./cmd/pdf-fts

            - name: Build for macOS ARM64
              run: |
                  GOOS=darwin GOARCH=arm64 go build -tags sqlite_fts5 -o pdf-fts-Darwin-arm64 ./cmd/pdf-fts

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                  files: |
                      pdf-fts-Linux-x86_64
                      pdf-fts-Linux-aarch64
                      pdf-fts-Darwin-x86_64
                      pdf-fts-Darwin-arm64
                      pdf-fts-Windows-x86_64.exe
                      pdf-fts-Windows-arm64.exe
                  generate_release_notes: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
